import Head from "next/head";
import styles from "../styles/styles.module.css";
import ProductCard from "../components/product";
import { Col, Row } from "antd";
import React from "react";
import { axiosInstance } from "../axios.js";
import { Elements } from "@stripe/react-stripe-js";
import { stripePromise } from "../stripe";
import { PageHeader } from "antd";
import { useRouter } from "next/router";

function Home({ unlockPacks }) {
  const router = useRouter();

  return (
    <div className="container">
      <Head>
        <title>Unlock Packs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ fontSize: "24px", marginTop: "36px" }}>
        <PageHeader
          className="site-page-header"
          onBack={() => router.push("/")}
          title="Unlock Perks"
          subTitle="Get access codes and post job cards"
        />
      </div>
      <main className={styles.main}>
        {/* <Typography.Title level={3} style={{ margin: 0, ma }}>
          Unlock Packs
        </Typography.Title> */}

        <Row gutter={16}>
          <Elements stripe={stripePromise}>
            {unlockPacks.map((pack) => {
              return (
                <Col key={pack.id} span={8}>
                  <ProductCard productData={pack} />
                </Col>
              );
            })}
          </Elements>
        </Row>
      </main>
    </div>
  );
}

export default Home;

const getPackages = async () => {
  const URL = "/products/unlock-packages/";

  try {
    const res = await axiosInstance.get(URL);
    if (res.status == 200) {
      return res.data.data;
    }
  } catch (err) {
    return null;
  }
};

export async function getStaticProps(context) {
  const unlockPacks = await getPackages();

  return {
    props: {
      unlockPacks: unlockPacks,
    },
  };
}
